### ISSUE TITLE
Tries to run multiline code in request

### ISSUE THREAD

**Issue by emsi** [iamgreggarcia/codesherpa#21]
Recently quite often I get this issue where ChatGPT tries to send a query with code spanning multiple lines. 

![image](https://github.com/iamgreggarcia/codesherpa/assets/433383/1da0806f-a0bb-42de-9e8e-690f49146942)

That's weird because not long time ago it used to work flawlessly.  Even if the code was first displayed with formatting it was passed to API in the correct format.

![image](https://github.com/iamgreggarcia/codesherpa/assets/433383/5fc57614-b358-43a4-9715-615fca72405a)

Not shure it it can be addressed with prompt or perhaps we could make the API resilient to that?

**Comment by iamgreggarcia** [comment]
How frequently is this happening?

I've had this issue before early on in development. I think this can be addressed a few ways: 

1. ensuring there is a correct example for that endpoint in the OpenAPI spec
2. updating the error handling such that the response is more informative for the model (it will usually self-correct and retry the request)
3. explicitly describing the format in the manifest `description_for_model` 

I'll look into each of these, though I think #2 is addressed in an upcoming update.

**Comment by emsi** [comment]
>     1. ensuring there is a correct example for that endpoint in the OpenAPI spec
> 
Pretty much every time. I think it started after https://github.com/iamgreggarcia/codesherpa/pull/19 but I might be wrong.

>     2. updating the error handling such that the response is more informative for the model (it will usually self-correct and retry the request)
> 
The worst part is that it does exactly the same like many times until it finally says that there was a technical error and it cannot continue. It looks like:
![image](https://github.com/iamgreggarcia/codesherpa/assets/433383/0c38a361-5535-4fa0-8f7d-6b9a968ab4cd)
Each of those requests end with:
```
ApiSyntaxError: Could not parse API call kwargs as JSON: exception=Invalid control character at: line 3 column 10 (char 33) url=http://localhost:3333/repl
```
I think the error message is not informative enough for the model to figure out what he (or it... I'm still confused by that ;) is doing wrong so he just tries again (pure madness).

> I'll look into each of these, though I think #2 is addressed in an upcoming update.

Thank you. 
What do you mean by  "upcoming update"? Is it somewhere in GitHub? Could I give it a try? I'm pretty comfortable with git.

**Comment by iamgreggarcia** [comment]
> What do you mean by "upcoming update"? Is it somewhere in GitHub? Could I give it a try? I'm pretty comfortable with git.

Of course! You can pull the `test` version of the docker image here: [ghcr.io/iamgreggarcia/codesherpa:test](https://github.com/iamgreggarcia/codesherpa/pkgs/container/codesherpa/107178900?tag=test), which corresponds to the `test` branch you can find here: [codesherpa/tree/test](https://github.com/iamgreggarcia/codesherpa/tree/test) 

I tested it out and it's working well again. In short, I added some response models to API endpoints that are now automatically incorporated into the OpenAPI spec. The API spec is looking much better. 

Let me know if you run into any issues or the same issue is persisting.


> The worst part is that it does exactly the same like many times until it finally says that there was a technical error and it cannot continue. It looks like:

I've encountered this in the past. The model should dynamically back off  when it gets 429s/500s in a short period of time. Adding rate-limiting to our end could also help.

**Comment by iamgreggarcia** [comment]
Let's try again. I've added even more explicit instructions for the model and have been able to get it to create and embed visualizations. The problem in your latest screenshot is the model did not save the visualization, but rather caled the `.show()` method. To see images with the plugin, however, the model must embed an image file in it's response markdown. The updated `description_for_model` should fix this.

Download the latest image (`sha256:24b314274a3e4e66175afff8d71782ea82936cd0397a0f67679dcbb93c0ba346`) with the test tag here: [ghcr.io/iamgreggarcia/codesherpa:test](https://github.com/iamgreggarcia/codesherpa/pkgs/container/codesherpa/107590781?tag=test). 

When running the API, you can see the updated `description_for_model` in the swagger UI at [localhost:3333/docs](http://localhost:3333/docs#/default/get_manifest__well_known_ai_plugin_json_get). 

Here's an example of a visualization embedded in the response (from a little bit ago):
![Screenshot from 2023-07-07 00-08-41](https://github.com/iamgreggarcia/codesherpa/assets/16596972/ae4e8818-ae38-4fb2-88a0-01cd33f89d1d)

![Screenshot from 2023-07-07 00-19-16](https://github.com/iamgreggarcia/codesherpa/assets/16596972/6bdb0a99-ab74-47f2-8b87-08dce0b163d6)

Note the last bit of code: 
```python
# Save the plot
generated_plot_path = 'static/images/correlation_heatmap.png'
plt.savefig(generated_plot_path)
```

The `.savefig` is what we want 😃 

Hope that helps!

**Comment by emsi** [comment]
Thank you for your effort! Now it worked off the bat! GPT even figured it needs to use `/command` to install missing package.
Oddly enough it still insisted on `plt.show()` though  but that's hardly an issue :)
```
# Save the plot
plt.savefig('static/images/venn_diagram.png')

# Display the plot
plt.show()
```

**Comment by iamgreggarcia** [comment]
Awesome! Glad it seems to be working again. I've merged the changes into main. The `latest` tagged image now has the changes.
